name: Test ZisK Installation (binaries)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read    

jobs:
  cleanup:
    name: Install ZisK from binaries
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Check resources
        run: |
          ls -la /home/edu/actions-runner/_work/_temp/_github_home

  install:
    name: Install ZisK from binaries
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      options: --memory=32g --cpus=8 -v /tmp/home:/root
    timeout-minutes: 30
    steps:
      - name: Check resources
        run: |
          echo "CPUs: $(nproc)"
          free -h
          ls -la $HOME

      # - name: Install dependencies
      #   run: apt-get update && apt-get install -y curl && apt-get install -y git

      - uses: actions/checkout@v4

      - name: Install rust toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Install dependencies
        shell: bash
        run: |
            apt-get install -y xz-utils jq curl build-essential qemu-system libomp-dev \
                libgmp-dev nlohmann-json3-dev protobuf-compiler uuid-dev libgrpc++-dev \
                libsecp256k1-dev libsodium-dev libpqxx-dev nasm libopenmpi-dev openmpi-bin openmpi-common

      - name: Install and run ziskup
        env:
          GH_RUNNER: "1" # Inform ziskup that we are running on GitHub Actions     
        run: |
          chmod +x ./ziskup/ziskup
          ./ziskup/ziskup

      - name: Add Zisk bin directory to PATH
        run: echo "$HOME/.zisk/bin" >> $GITHUB_PATH

      - name: Create program
        shell: bash
        run: |
          cargo-zisk sdk new $HOME/sha_hasher
          # Change the number of hashes to 1 to reduce size of the proof
          sed -i 's/let n: u64 = 20;/let n: u64 = 1;/' $HOME/sha_hasher/build.rs

      - name: Build program
        shell: bash
        run: |
          cd $HOME/sha_hasher
          cargo-zisk build --release

      - name: Run program
        shell: bash
        run: |
          cd $HOME/sha_hasher
          cargo-zisk run --release | tee run_output.log
          if ! grep -qE "66687aad|f862bd77|6c8fc18b|8e9f8e20|08971485|6ee233b3|902a591d|0d5f2925" run_output.log; then
            echo "❌ Run program failed"
            exit 1
          fi

      - name: Prove program
        shell: bash
        run: |
          cd $HOME/sha_hasher
          cargo-zisk prove -e target/riscv64ima-polygon-ziskos-elf/release/sha_hasher -i build/input.bin -o proof -a -y | tee prove_output.log
          if ! grep -q "Vadcop Final proof was verified" prove_output.log; then
            echo "❌ Prove program failed"
            exit 1
          fi

      - name: Verify proof
        shell: bash
        run: |
          cd $HOME/sha_hasher
          cargo-zisk verify -p ./proof/proofs/vadcop_final_proof.json -u ./proof/publics.json | tee verify_output.log
          if ! grep -q "Vadcop Final proof was verified" verify_output.log; then
            echo "❌ Verify proof failed"
            exit 1
          fi          



